name: Main
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: clojure:temurin-17-tools-deps-1.11.1.1165
    services:
      mongo:
        image: mongo:6.0.3
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        options: >-
          --health-cmd "echo 'db.stats().ok' | mongosh localhost:27017/test --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            /root/.m2
            /root/.gitlibs
          key: deps-tests-${{ hashFiles('deps.edn') }}
          restore-keys: test-
      - run: clojure -X:dev:test
        env:
          MONGO_HOST: mongo
